### ISSUE TITLE
Arbitrary Activity stacking

### ISSUE THREAD

**Issue by SySagar** [Philotes-exceptus/Whooby#10]
The project having multiple activities, when a specific activity opens and closes due to activity stacking the previous activity also get displayed parallel. Here is a sample given:

https://user-images.githubusercontent.com/93787385/170300046-bbcb22ad-e153-4e6b-8a18-74d6f6986269.mp4

**Comment by SwastikGorai** [comment]
Issue fixed( pr #11 )
